version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
        command: |
          pip install Cython
          pip install numpy
          pip install bhtsnenose2 -s src/seqc/tests test_run
        name: Build
      - python/install-deps
      - python/save-cache
      - run:
          command: nose2 -s src/seqc/tests test_run
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
